### ISSUE TITLE
Issues if I change kernel values

### ISSUE THREAD

**Issue by ambikaverma** [rayryeng/laplacianBlend#2]
I tried to change the kernel values to the following -

ker=(1/16)*[1 4 6 4 1;4 16 24 16 4;6 24 36 24 6;4 16 24 16 4; 1 4 6 4 1]; in the generating_kernel function.

Doing this I get a very odd output - 
![image](https://user-images.githubusercontent.com/23284511/27246947-a70a9176-52ba-11e7-96b8-4f49beb62b1b.png)

I have tried this for a number of images, but the right side image is always looking odd. 
I'm surprised as to how it can work for one image and not for the other.

**Comment by rayryeng** [comment]
@ambikaverma 

This is because the kernel you proposed is **not normalized**.  If you look at the kernel provided previously, the sum of all of the elements is equal to 1.  Your kernel even though it's multiplied by `(1 / 
 16)`, the summation of all elements does not equal 1.  It would be `(1 / 16)` for the 1D version of the kernel: `ker = [1 4 6 4 1]`.  However, because you have an additional degree of freedom when you do the outer product (`ker' * ker` will give you the proposed kernel without the `(1 / 16)` factor), it must now be normalized by `(1 / 256)` instead of `(1 / 16)`.  Therefore, you can fix this by specifying the normalization factor as `(1 / 256)` instead of `(1 / 16)`:

```
% Function that generates a 5 x 5 filtering kernel
% used for Laplacian Pyramidal blending
% a is usually 0.4
function [ker] = generating_kernel(a)
    %w_1d = [0.25 - a/2 0.25 a 0.25 0.25 - a/2];
    %ker = w_1d' * w_1d;
    ker = (1/256) * [1 4 6 4 1;4 16 24 16 4;6 24 36 24 6;4 16 24 16 4; 1 4 6 4 1];
end
```

When you do this, I get the following image:

![new_kernel](https://user-images.githubusercontent.com/765375/27255361-f07e6a70-536a-11e7-8e1d-f8ffaff3b410.png)

In the future when you specify new kernels, instead of knowing before hand what the normalization factor is, compute this yourself by summing up all of the elements in the kernel and dividing each element by that amount.  This allows you to not think about it and it will produce the right kernel each time.

Something like this will work:

```
% Function that generates a 5 x 5 filtering kernel
% used for Laplacian Pyramidal blending
% a is usually 0.4
function [ker] = generating_kernel(a)
    %w_1d = [0.25 - a/2 0.25 a 0.25 0.25 - a/2];
    %ker = w_1d' * w_1d;
    ker = [1 4 6 4 1;4 16 24 16 4;6 24 36 24 6;4 16 24 16 4; 1 4 6 4 1];
    ker = ker / sum(ker(:));
end
```

Notice that we don't multiply the kernel with a constant anymore and that is deferred to later when we compute the normalization constant and we divide each value in the kernel element-wise by this amount.

Closing your issue now as I've adequately solved your problem.
